### ISSUE TITLE
Vue component won't render

### ISSUE THREAD

**Issue by janat08** [meteor-vue/blaze-integration#4]
Sure enough one of core functions refuses to work for me:
```
<template name="AppLayout">
    {{> VueComponent component="filters"}}
</template>
```
Was looking to pass router view in there.

**Comment by janat08** [comment]
Render slot is undefined it says in blaze template.

**Comment by mitar** [comment]
I think this is some other issue on your side. Maybe in `filters` component.

**Comment by janat08** [comment]
Ye, I suppose it's vuex or something. #3
