### ISSUE TITLE
Possible to remove the dependency on peerlibrary:data-lookup?

### ISSUE THREAD

**Issue by IamCarbonMan** [meteor-vue/blaze-integration#6]
This package hasn't been updated since 2015 and currently pulls in CoffeeScript 1 as a dependency, which messes up projects that want to use Coffeescript 2.

**Comment by IamCarbonMan** [comment]
It should also be noted that the library is less than 30 lines of Coffeescript code and should be easy to reimplement if that's found to be necessary.

**Comment by mitar** [comment]
Yes, it has not been updated because it works well.

**Comment by mitar** [comment]
I do not think dependency on CoffeeScript 1 should mess with anything because it is just a compile time dependency?

**Comment by mitar** [comment]
So what exactly happens?

**Comment by IamCarbonMan** [comment]
If you run the following commands in order:

```
meteor add coffeescript
meteor add vuejs:blaze-integration
```
 The following error occurs:

```
  => Errors while adding packages:
 While selecting package versions:
 error: Potentially incompatible change required to top-level dependency: coffeescript 1.12.6_1, was
 2.0.3_1.
 Constraints on package "coffeescript":
 * coffeescript@1.0.5 <- peerlibrary:data-lookup 0.1.0 <- vuejs:blaze-integration 0.2.0
 * coffeescript@1.0.5 <- peerlibrary:computed-field 0.3.1 <- peerlibrary:data-lookup 0.1.0 <-
 vuejs:blaze-integration 0.2.0
To allow potentially incompatible changes to top-level dependencies, you must pass
--allow-incompatible-update on the command line.
```

Rerunning the command using the --allow-incompatible-update option allows installing vuejs:blaze-integration, but in the process the top-level coffeescript dependency is downgraded to 1.12.6_1.

**Comment by mitar** [comment]
A new version of peerlibrary:data-lookup has been releases with CoffeeScript 2 support. I believe you can update to it without a new release of this package.
