### ISSUE TITLE
Dynamic data to blaze template seems non reactive

### ISSUE THREAD

**Issue by mathieustan** [meteor-vue/blaze-integration#9]
Hello again.

I'm using :data to pass data to a blaze template. 
When I log data in my blaze template, It works but it doesn't seem to be reactive. 

When data change in my vue component, Blaze template doesn't see any change. 

exemple : 
`<blaze-template :data="{data}" template="template />`

in Blaze Template : 
```
self.autorun(() => {
  console.log(Template.currentData()); // data object is present, but never change
})
```

Any idea ?

**Comment by mitar** [comment]
Have you seen this in README:

> You have to use Tracker-enabled fork of Vue and fork of Tracker. See these instructions for more information.

**Comment by mathieustan** [comment]
I saw it ... but though it could work without... crap.
Even if i'm using vue-meteor-tracker ?

**Comment by mitar** [comment]
Those are two different approaches. Tracker-enabled fork makes it so that you can use both Vue and Tracker reactivity together. And when you are combining Vue and Blaze you do not need that.

**Comment by mathieustan** [comment]
We are migrating from Blaze to Vue (and I need to do it progressivily). 
So, I still have some blaze template, and I'm starting to create vue components to replace them. 
I succeed to make a lot working with vuex, vue-supply & meteor-vue-tracker.  But I'still have this issue where :data isn't reactive in Blaze ... 
We are running in production, and we don't want to use a fork a vue :( I think I don't have another solution.

**Comment by mitar** [comment]
Yea, I made a fork of  vue to solve this migration issue and make it easy to migrate.

I think fork is production ready.

**Comment by mathieustan** [comment]
thx alot for your reactivity.
